import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Yith from "@yith/yith";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Yith</h1>

        <p className={styles.description}>
          Yith is a component library that interweaves IIIF manifests and their
          content into flexible layouts in a usable, responsive, and accessible
          way.
        </p>

        <Yith type="projection">
          <Yith.Manifest id="https://api.artic.edu/api/v1/artworks/18979/manifest.json" />
          <Yith.Manifest id="https://iiif.harvardartmuseums.org/manifests/object/169542">
            <Yith.Canvas id="https://iiif.harvardartmuseums.org/manifests/object/169542/canvas/canvas-469446512" />
            <Yith.Canvas id="https://iiif.harvardartmuseums.org/manifests/object/169542/canvas/canvas-469454932" />
          </Yith.Manifest>
          <Yith.Manifest id="https://yith.dev/fixtures/iiif/manifests/the-emperor-sailing.json">
            <Yith.Annotation id="https://yith.dev/fixtures/iiif/manifests/the-emperor-sailing/canvas/1/annotations/1" />
            <Yith.Annotation id="https://yith.dev/fixtures/iiif/manifests/the-emperor-sailing/canvas/1/annotations/2" />
            <Yith.Annotation id="https://yith.dev/fixtures/iiif/manifests/the-emperor-sailing/canvas/1/annotations/3" />
          </Yith.Manifest>
        </Yith>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
